# Build the surge-fx with JUCE buidls

trigger:
- master

pr:
- master

jobs:
- job: Build
  strategy:
    matrix:
      mac10:
        imageName: 'macos-10.13'
        isMac: true

  pool:
    vmImage: $(imageName)

  steps:
  - checkout: self
    fetchDepth: 1
    # submodules: recursive # can't do submodules here b'cuz depth=1 fails with Github


  - bash: |
      git submodule update --init --recursive
    displayName: Get Surge SubModule

  - bash: |
      make all
    displayName: Build Mac Plugins
    condition: variables.isMac
